language: rust
rust:
    - stable
    - beta
    - nightly

script:
  - ./bootstrap.sh
  - git diff --exit-code # Check that src/grammar.rs is updated to match src/grammar.rustpeg
  - cargo test
  - (cd peg-tests && cargo test)
  - (test $TRAVIS_RUST_VERSION != "nightly" || (cd peg-syntax-ext && cargo test))
