[package]
name = "peg-macros"
version = "0.6.3"
authors = [ "Kevin Mehall <km@kevinmehall.net>" ]
license = "MIT"
repository = "https://github.com/kevinmehall/rust-peg"
description = "Procedural macros for rust-peg. To use rust-peg, see the `peg` crate."
edition = "2018"

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
peg-runtime = { version = "= 0.6.3", path = "../peg-runtime" }

[features]
trace = []

[lib]
proc-macro = true
name = "peg_macros"
path = "lib.rs"

[[bin]]
name = "rust-peg"
path = "bin.rs"
test = false
bench = false
